services:

  postgres:
    image: postgres:16
    container_name: olist-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 5s
      timeout: 5s
      retries: 5


  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: olist-mlflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mlflow_artifacts:/mlartifacts
    command:
      - mlflow
      - server
      - --host
      - "0.0.0.0"
      - --port
      - "5000"
      - --backend-store-uri
      - "postgresql://mlflow:mlflow@postgres:5432/mlflow"
      - --artifacts-destination
      - "file:///mlartifacts"
      - --allowed-hosts
      - "localhost:*,127.0.0.1:*,mlflow:*"


  mlflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist-mlflow-init
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command:
      - python
      - -m
      - src.mlflow_tracking


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist-api
    depends_on:
      mlflow-init:
        condition: service_completed_successfully
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"


volumes:
  postgres_data:
  mlflow_artifacts: